/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Nicolas Herrera
 */
public class VentanaBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBiblioteca
     */
    public VentanaBiblioteca() {
        initComponents();
        this.pagMultaUsuario();
        this.addBotonesPrincipalListener(new CambiarPaginaListener());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpEncabezado = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        jpMenu = new javax.swing.JPanel();
        jpMenuUsuario = new javax.swing.JPanel();
        btnLibrosUsuario = new javax.swing.JButton();
        btnPrestamosUsuario = new javax.swing.JButton();
        btnMultasUsuario = new javax.swing.JButton();
        btnSolicitudUsuario = new javax.swing.JButton();
        jpContenido = new javax.swing.JPanel();
        jpLibroUsuario = new javax.swing.JPanel();
        jpSuperiorLibroU = new javax.swing.JPanel();
        lblTituloLibroU = new javax.swing.JLabel();
        jpInferiorLibroU = new javax.swing.JPanel();
        jpIzquierdaLibroU = new javax.swing.JPanel();
        jpDerechaLibroU = new javax.swing.JPanel();
        jpsTablaLibroU = new javax.swing.JScrollPane();
        jtTablaLibroU = new javax.swing.JTable();
        jpPrestamoUsuario = new javax.swing.JPanel();
        jpSuperiorPrestamoU = new javax.swing.JPanel();
        lblTituloPrestamoU = new javax.swing.JLabel();
        jpInferiorPrestamoU = new javax.swing.JPanel();
        jpIzquierdaPrestamoU = new javax.swing.JPanel();
        jpDerechaPrestamoU = new javax.swing.JPanel();
        jpsTablaPrestamoU = new javax.swing.JScrollPane();
        jtTablaPrestamoU = new javax.swing.JTable();
        jpMultaUsuario = new javax.swing.JPanel();
        jpsTablaMultaU = new javax.swing.JScrollPane();
        jtTablaMultaU = new javax.swing.JTable();
        jpSuperiorMultaU = new javax.swing.JPanel();
        lblMultasTitulo = new javax.swing.JLabel();
        jpInferiorMultaU = new javax.swing.JPanel();
        jpIzquierdaMultaU = new javax.swing.JPanel();
        jpDerechaMultaU = new javax.swing.JPanel();
        jpSolicitudUsuario = new javax.swing.JPanel();
        jpFormularioSolicitudU = new javax.swing.JPanel();
        lblIsbnSolicitudU = new javax.swing.JLabel();
        txtIsbnSolicitudU = new javax.swing.JTextField();
        lblTituloSolicitudU = new javax.swing.JLabel();
        txtTituloSolicitudU = new javax.swing.JTextField();
        lblDescripcionSolicitudU = new javax.swing.JLabel();
        jpsDescripcionSolicitudU = new javax.swing.JScrollPane();
        txaDescripcionSolicitudU = new javax.swing.JTextArea();
        btnEnviarSolicitudU = new javax.swing.JButton();
        lblTituloSolicitudesU = new javax.swing.JLabel();
        jpsTablaSolicitudU = new javax.swing.JScrollPane();
        jtTablaSolicitudU = new javax.swing.JTable();
        jpIzquierdaSolicitudU = new javax.swing.JPanel();
        jpDerechaSolicitudUsuario = new javax.swing.JPanel();
        jpInferiorSolicitudU = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpEncabezado.setBackground(new java.awt.Color(225, 232, 239));
        jpEncabezado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 40, 10));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoUnivalleS.png"))); // NOI18N
        jpEncabezado.add(lblIcono);

        lblTitulo.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblTitulo.setText("BIBLIOTECA UNIVERSITARIA");
        jpEncabezado.add(lblTitulo);

        btnUsuario.setBackground(new java.awt.Color(235, 238, 243));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        btnUsuario.setFocusPainted(false);
        jpEncabezado.add(btnUsuario);

        getContentPane().add(jpEncabezado, java.awt.BorderLayout.PAGE_START);

        jpMenu.setLayout(new java.awt.CardLayout());

        jpMenuUsuario.setBackground(new java.awt.Color(235, 238, 243));
        jpMenuUsuario.setLayout(new java.awt.GridBagLayout());

        btnLibrosUsuario.setBackground(new java.awt.Color(225, 232, 239));
        btnLibrosUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnLibrosUsuario.setText("LIBROS");
        btnLibrosUsuario.setActionCommand("libroUsuario");
        btnLibrosUsuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 0, 10);
        jpMenuUsuario.add(btnLibrosUsuario, gridBagConstraints);

        btnPrestamosUsuario.setBackground(new java.awt.Color(225, 232, 239));
        btnPrestamosUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnPrestamosUsuario.setText("PRESTAMOS");
        btnPrestamosUsuario.setActionCommand("prestamoUsuario");
        btnPrestamosUsuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 0, 10);
        jpMenuUsuario.add(btnPrestamosUsuario, gridBagConstraints);

        btnMultasUsuario.setBackground(new java.awt.Color(225, 232, 239));
        btnMultasUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnMultasUsuario.setText("MULTAS");
        btnMultasUsuario.setActionCommand("multasUsuario");
        btnMultasUsuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(100, 10, 100, 10);
        jpMenuUsuario.add(btnMultasUsuario, gridBagConstraints);

        btnSolicitudUsuario.setBackground(new java.awt.Color(225, 232, 239));
        btnSolicitudUsuario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnSolicitudUsuario.setText("SOLICITUDES");
        btnSolicitudUsuario.setActionCommand("solicitudUsuario");
        btnSolicitudUsuario.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 100, 10);
        jpMenuUsuario.add(btnSolicitudUsuario, gridBagConstraints);

        jpMenu.add(jpMenuUsuario, "card2");

        getContentPane().add(jpMenu, java.awt.BorderLayout.WEST);

        jpContenido.setBackground(new java.awt.Color(249, 250, 252));
        jpContenido.setLayout(new java.awt.CardLayout());

        jpLibroUsuario.setOpaque(false);
        jpLibroUsuario.setLayout(new java.awt.BorderLayout(10, 10));

        jpSuperiorLibroU.setOpaque(false);

        lblTituloLibroU.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblTituloLibroU.setText("LIBROS");
        jpSuperiorLibroU.add(lblTituloLibroU);

        jpLibroUsuario.add(jpSuperiorLibroU, java.awt.BorderLayout.PAGE_START);

        jpInferiorLibroU.setOpaque(false);
        jpLibroUsuario.add(jpInferiorLibroU, java.awt.BorderLayout.PAGE_END);

        jpIzquierdaLibroU.setOpaque(false);
        jpLibroUsuario.add(jpIzquierdaLibroU, java.awt.BorderLayout.WEST);

        jpDerechaLibroU.setOpaque(false);
        jpLibroUsuario.add(jpDerechaLibroU, java.awt.BorderLayout.EAST);

        jtTablaLibroU.getTableHeader().setFont(new java.awt.Font("Montserrat",0, 12));
        jtTablaLibroU.setDefaultEditor(Object.class, null);
        jtTablaLibroU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtTablaLibroU.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "ISBN", "TITULO", "AUTOR", "EDITORIAL", "PUBLICACION", "IDIOMA", "# PAGINAS", "EJEMPLARES", "DIGITAL"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaLibroU.getTableHeader().setResizingAllowed(false);
        jtTablaLibroU.getTableHeader().setReorderingAllowed(false);
        jpsTablaLibroU.setViewportView(jtTablaLibroU);

        jpLibroUsuario.add(jpsTablaLibroU, java.awt.BorderLayout.CENTER);

        jpContenido.add(jpLibroUsuario, "libroUsuario");

        jpPrestamoUsuario.setOpaque(false);
        jpPrestamoUsuario.setLayout(new java.awt.BorderLayout(10, 10));

        jpSuperiorPrestamoU.setOpaque(false);

        lblTituloPrestamoU.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblTituloPrestamoU.setText("PRESTAMOS");
        jpSuperiorPrestamoU.add(lblTituloPrestamoU);

        jpPrestamoUsuario.add(jpSuperiorPrestamoU, java.awt.BorderLayout.PAGE_START);

        jpInferiorPrestamoU.setOpaque(false);
        jpPrestamoUsuario.add(jpInferiorPrestamoU, java.awt.BorderLayout.PAGE_END);

        jpIzquierdaPrestamoU.setOpaque(false);
        jpPrestamoUsuario.add(jpIzquierdaPrestamoU, java.awt.BorderLayout.WEST);

        jpDerechaPrestamoU.setOpaque(false);
        jpPrestamoUsuario.add(jpDerechaPrestamoU, java.awt.BorderLayout.EAST);

        jtTablaPrestamoU.getTableHeader().setFont(new java.awt.Font("Montserrat", 0, 12));
        jtTablaPrestamoU.setDefaultEditor(Object.class, null);
        jtTablaPrestamoU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtTablaPrestamoU.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "# PRESTAMO", "FECHA REALIZACION", "ISBN", "# EJEMPLAR", "FECHA DEVOLUCION", "EMPLEADO"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaPrestamoU.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTablaPrestamoU.getTableHeader().setResizingAllowed(false);
        jtTablaPrestamoU.getTableHeader().setReorderingAllowed(false);
        jpsTablaPrestamoU.setViewportView(jtTablaPrestamoU);

        jpPrestamoUsuario.add(jpsTablaPrestamoU, java.awt.BorderLayout.CENTER);

        jpContenido.add(jpPrestamoUsuario, "prestamoUsuario");

        jpMultaUsuario.setOpaque(false);
        jpMultaUsuario.setLayout(new java.awt.BorderLayout(10, 10));

        jtTablaMultaU.getTableHeader().setFont(new java.awt.Font("Montserrat", 0, 12));
        jtTablaMultaU.setDefaultEditor(Object.class, null);
        jtTablaMultaU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtTablaMultaU.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"1", "0000", "1", "24/87/21", "5000", "Hola"},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "# MULTA", "ISBN", "# EJEMPLAR", "FECHA MULTA", "VALOR", "DESCRIPCION"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaMultaU.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTablaMultaU.getTableHeader().setResizingAllowed(false);
        jtTablaMultaU.getTableHeader().setReorderingAllowed(false);
        jpsTablaMultaU.setViewportView(jtTablaMultaU);

        jpMultaUsuario.add(jpsTablaMultaU, java.awt.BorderLayout.CENTER);

        jpSuperiorMultaU.setOpaque(false);

        lblMultasTitulo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblMultasTitulo.setText("MULTAS");
        jpSuperiorMultaU.add(lblMultasTitulo);

        jpMultaUsuario.add(jpSuperiorMultaU, java.awt.BorderLayout.PAGE_START);

        jpInferiorMultaU.setOpaque(false);
        jpMultaUsuario.add(jpInferiorMultaU, java.awt.BorderLayout.SOUTH);

        jpIzquierdaMultaU.setOpaque(false);
        jpMultaUsuario.add(jpIzquierdaMultaU, java.awt.BorderLayout.LINE_END);

        jpDerechaMultaU.setOpaque(false);
        jpMultaUsuario.add(jpDerechaMultaU, java.awt.BorderLayout.LINE_START);

        jpContenido.add(jpMultaUsuario, "multaUsuario");

        jpSolicitudUsuario.setOpaque(false);
        jpSolicitudUsuario.setLayout(new java.awt.BorderLayout(10, 10));

        jpFormularioSolicitudU.setOpaque(false);
        jpFormularioSolicitudU.setLayout(new java.awt.GridBagLayout());

        lblIsbnSolicitudU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblIsbnSolicitudU.setText("ISBN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jpFormularioSolicitudU.add(lblIsbnSolicitudU, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jpFormularioSolicitudU.add(txtIsbnSolicitudU, gridBagConstraints);

        lblTituloSolicitudU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblTituloSolicitudU.setText("TITULO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jpFormularioSolicitudU.add(lblTituloSolicitudU, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jpFormularioSolicitudU.add(txtTituloSolicitudU, gridBagConstraints);

        lblDescripcionSolicitudU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblDescripcionSolicitudU.setText("DESCRIPCION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jpFormularioSolicitudU.add(lblDescripcionSolicitudU, gridBagConstraints);

        txaDescripcionSolicitudU.setColumns(20);
        txaDescripcionSolicitudU.setRows(5);
        jpsDescripcionSolicitudU.setViewportView(txaDescripcionSolicitudU);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        jpFormularioSolicitudU.add(jpsDescripcionSolicitudU, gridBagConstraints);

        btnEnviarSolicitudU.setBackground(new java.awt.Color(255, 0, 0));
        btnEnviarSolicitudU.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnEnviarSolicitudU.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarSolicitudU.setText("ENVIAR");
        btnEnviarSolicitudU.setBorderPainted(false);
        btnEnviarSolicitudU.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jpFormularioSolicitudU.add(btnEnviarSolicitudU, gridBagConstraints);

        lblTituloSolicitudesU.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblTituloSolicitudesU.setText("SOLICITUDES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        jpFormularioSolicitudU.add(lblTituloSolicitudesU, gridBagConstraints);

        jpSolicitudUsuario.add(jpFormularioSolicitudU, java.awt.BorderLayout.NORTH);

        jpsTablaSolicitudU.setOpaque(false);

        jtTablaSolicitudU.getTableHeader().setFont(new java.awt.Font("Montserrat", 0
                , 12));
        jtTablaSolicitudU.setDefaultEditor(Object.class, null);
        jtTablaSolicitudU.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtTablaSolicitudU.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "# SOLICITUD", "ISBN", "TITULO", "DESCRIPCION"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaSolicitudU.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTablaSolicitudU.getTableHeader().setResizingAllowed(false);
        jtTablaSolicitudU.getTableHeader().setReorderingAllowed(false);
        jpsTablaSolicitudU.setViewportView(jtTablaSolicitudU);

        jpSolicitudUsuario.add(jpsTablaSolicitudU, java.awt.BorderLayout.CENTER);

        jpIzquierdaSolicitudU.setOpaque(false);
        jpSolicitudUsuario.add(jpIzquierdaSolicitudU, java.awt.BorderLayout.WEST);

        jpDerechaSolicitudUsuario.setOpaque(false);
        jpSolicitudUsuario.add(jpDerechaSolicitudUsuario, java.awt.BorderLayout.EAST);

        jpInferiorSolicitudU.setOpaque(false);
        jpSolicitudUsuario.add(jpInferiorSolicitudU, java.awt.BorderLayout.SOUTH);

        jpContenido.add(jpSolicitudUsuario, "solicitudUsuario");

        getContentPane().add(jpContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBiblioteca().setVisible(true);
            }
        });
    }

    public void pagMultaUsuario()
    {
        CardLayout a = (CardLayout)jpContenido.getLayout();
        a.show(jpContenido, "multaUsuario");
    }

    public void pagSolicitudUsuario()
    {
        CardLayout a = (CardLayout)jpContenido.getLayout();
        a.show(jpContenido, "solicitudUsuario");
    }

    public void pagPrestamoUsuario()
    {
        CardLayout a = (CardLayout)jpContenido.getLayout();
        a.show(jpContenido, "prestamoUsuario");
    }

    public void pagLibroUsuario()
    {
        CardLayout a = (CardLayout)jpContenido.getLayout();
        a.show(jpContenido, "libroUsuario");
    }


    class CambiarPaginaListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            if (e.getActionCommand().equalsIgnoreCase("multasUsuario"))
            {
                pagMultaUsuario();
            }
            if (e.getActionCommand().equalsIgnoreCase("solicitudUsuario"))
            {
                pagSolicitudUsuario();
            }
            if (e.getActionCommand().equalsIgnoreCase("prestamoUsuario"))
            {
                pagPrestamoUsuario();
            }
            if (e.getActionCommand().equalsIgnoreCase("libroUsuario"))
            {
                pagLibroUsuario();
            }
            limpiarMultaUsuario();
        }
    }

    public void addBotonesPrincipalListener(ActionListener listenControles)
    {
        btnMultasUsuario.addActionListener(listenControles);
        btnSolicitudUsuario.addActionListener(listenControles);
        btnPrestamosUsuario.addActionListener(listenControles);
        btnLibrosUsuario.addActionListener(listenControles);
    }

    public void limpiarMultaUsuario()
    {
        txtIsbnSolicitudU.setText("");
        txtTituloSolicitudU.setText("");
        txaDescripcionSolicitudU.setText("");
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnEnviarSolicitudU;
    private javax.swing.JButton btnLibrosUsuario;
    private javax.swing.JButton btnMultasUsuario;
    private javax.swing.JButton btnPrestamosUsuario;
    private javax.swing.JButton btnSolicitudUsuario;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpDerechaLibroU;
    private javax.swing.JPanel jpDerechaMultaU;
    private javax.swing.JPanel jpDerechaPrestamoU;
    private javax.swing.JPanel jpDerechaSolicitudUsuario;
    private javax.swing.JPanel jpEncabezado;
    private javax.swing.JPanel jpFormularioSolicitudU;
    private javax.swing.JPanel jpInferiorLibroU;
    private javax.swing.JPanel jpInferiorMultaU;
    private javax.swing.JPanel jpInferiorPrestamoU;
    private javax.swing.JPanel jpInferiorSolicitudU;
    private javax.swing.JPanel jpIzquierdaLibroU;
    private javax.swing.JPanel jpIzquierdaMultaU;
    private javax.swing.JPanel jpIzquierdaPrestamoU;
    private javax.swing.JPanel jpIzquierdaSolicitudU;
    private javax.swing.JPanel jpLibroUsuario;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuUsuario;
    private javax.swing.JPanel jpMultaUsuario;
    private javax.swing.JPanel jpPrestamoUsuario;
    private javax.swing.JPanel jpSolicitudUsuario;
    private javax.swing.JPanel jpSuperiorLibroU;
    private javax.swing.JPanel jpSuperiorMultaU;
    private javax.swing.JPanel jpSuperiorPrestamoU;
    private javax.swing.JScrollPane jpsDescripcionSolicitudU;
    private javax.swing.JScrollPane jpsTablaLibroU;
    private javax.swing.JScrollPane jpsTablaMultaU;
    private javax.swing.JScrollPane jpsTablaPrestamoU;
    private javax.swing.JScrollPane jpsTablaSolicitudU;
    private javax.swing.JTable jtTablaLibroU;
    private javax.swing.JTable jtTablaMultaU;
    private javax.swing.JTable jtTablaPrestamoU;
    private javax.swing.JTable jtTablaSolicitudU;
    private javax.swing.JLabel lblDescripcionSolicitudU;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIsbnSolicitudU;
    private javax.swing.JLabel lblMultasTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloLibroU;
    private javax.swing.JLabel lblTituloPrestamoU;
    private javax.swing.JLabel lblTituloSolicitudU;
    private javax.swing.JLabel lblTituloSolicitudesU;
    private javax.swing.JTextArea txaDescripcionSolicitudU;
    private javax.swing.JTextField txtIsbnSolicitudU;
    private javax.swing.JTextField txtTituloSolicitudU;
    // End of variables declaration
}
